### ISSUE TITLE
Use an Object Array as input data

### ISSUE THREAD

**Issue by damibarbieri** [samccone/paper-typeahead#10]
The idea is to support Objects as Array elements and pass the selected Object to the host element. Filtering it by a porperty which should be passed from the host element to the paper-typeahead. The idea is meant to support Objects with an ID, I am not sure if this should be done this way or there is a better workaround.

**Comment by godinger** [comment]
I have the same requirement. My suggestion is that it would work as follows:
If objects are of format: { fname: "foo", lname: "bar", id: 123}
It would be able to list choices either by specifying a field (fname) or a function (that could, for example, combine fields so that full name is displayed, or even something like "foo bar (123)"), and when the item is selected you'd have access to the associated object.

A property could named "item-label-property" to allow a property to be used as the text. Similarly, there could be a property named "item-value-property" to specify which item's property is used for the item's value when the item is selected. "item-label-function" could be used to allow a function to be used to determine display values.

If support for a function is much more difficult, I think that is a more advanced requirement, and would be glad to have support for item-label-property and item-value-property for now.
